### PR TITLE
In 'msrsave -r FILE', if writing an MSR value fails, warn user but co…

### PR DESCRIPTION
**Pull request by cmcantalupo**
…ntinue.

- When using the msrsave utility, there may be cases where a whitelist
  enables MSRs that are not available on the particular SKU booted in
  a particular configuration.
- One example of this is that the number of programmable counters per CPU
  doubles when hyperthreading is disabled in the BIOS on Skylake
  architectures.
- This patch will enable msrsave to issue a warning for this case, but
  restore all values that can be written.

Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

### CODE REVIEW

**Comment by cmcantalupo** [comment]
@slabasan, @rountree Can we merge this PR?  Also, will there be another tag of msr-safe before SC18?  I would like to get the openhpc package for msr-safe up to date with this patch so that save / restore works on SKX when hyperthreading is enabled.

**Comment by slabasan** [comment]
I can work on the merge now, should be done within the hour. We do not currently have plans to release a new tag of msr-safe before SC18, but if an updated tag is helpful for inclusion in OpenHPC, we'd be happy to make a tag. Let us know.

**Comment by slabasan** [comment]
@cmcantalupo This has been merged here `46a4fd6`. I will close this PR. If you would like a tagged version for the OpenHPC package, please let us know.

**Comment by cmcantalupo** [comment]
Thanks @slabasan.  I can't guarantee that we will get the update into OpenHPC in time(they are close to tagging 1.3.6), but a tag of msr-safe rather than a set of patches would get through the OpenHPC review process much faster.  If it isn't too much trouble a 1.2.1 tag of the tip of master would be a big help.  Thanks!

**Comment by slabasan** [comment]
@cmcantalupo: Tag v1.2.1 completed -- https://github.com/LLNL/msr-safe/releases/tag/v1.2.1

**Comment by cmcantalupo** [comment]
@slabasan Thanks!

**Pull request closed without merging**
