### PR TITLE
Add MSR_UNCORE_RATIO_LIMIT

### PR DESCRIPTION
**Pull request by bgeltz**
- Introduced in Haswell timeframe.

Signed-off-by: Brad Geltz <brad.geltz@intel.com>

### CODE REVIEW

**Comment by bgeltz** [comment]
Added in response to geopm/geopm#665.

@cmcantalupo @slabasan Please take a look when you have a moment.

**Comment by bgeltz** [comment]
```
wl_062a - SNB = NO
wl_062d - SNB = NO
wl_063c - IVT = NO
wl_063e - IVT = NO
wl_063f - HSX = Yes
wl_0645 - HSW = Yes
wl_0646 - HSW = Yes
wl_064f - BDX = Yes
wl_0655 - SKX = Yes
wl_0657 - KNL = Yes
```

**Comment by cmcantalupo** [comment]
LGTM

**Comment by slabasan** [comment]
Looks good to me, too. Thanks for contributing this. Will get this merged in today.

**Comment by TomTheBear** [comment]
Just as remark: The current Uncore frequency can be read from register 0x621 bits 0-6

**Comment by cmcantalupo** [comment]
Thanks @TomTheBear.  Seems like 0x621 would be a good register to have read access to if we have write access to set the uncore frequency.

**Comment by TomTheBear** [comment]
You're welcome. That's how LIKWID gets the current frequency to avoid programming Uncore HW counters. LIKWID supports msr-safe, so it would be beneficial when both registers are accessible.

**Comment by slabasan** [comment]
Thanks @TomTheBear -- Do we know if 0x621 was also introduced in the Haswell timeframe? Should it be in the same whitelists as 0x620?

**Comment by TomTheBear** [comment]
Yes, it's available on the same platforms as MSR_UNCORE_RATIO_LIMIT.

In your platform list are some platforms missing which support these registers. At least my Haswell system (063C) supports MSR_UNCORE_RATIO_LIMIT (0x620) and MSR_UNCORE_FREQ (0x621). But it is a desktop and you mainly concentrate on server chips. Missing server chips would be Broadwell E3 (0647) and Broadwell D (0656). CLX is somehow included as it uses the same model ID as SKX (but can be differentiated by the stepping)

**Comment by bgeltz** [comment]
Let me see if I can get this PR updated to include 0x621.  I'll update in a little bit.  Thanks for the information @TomTheBear.

**Comment by slabasan** [comment]
@bgeltz Thanks! I actually merged in this PR this morning. When you are able to add 0x621, can you please make a new PR? Apologies for the inconvenience.

**Comment by bgeltz** [comment]
No prob.  I'll put that work in a new PR.  I thought that the patch was still un-merged because this PR was still open.  It looks like you pushed it into dev by hand, which is fine w/me.

I'll close this since the patch is in master now.

**Comment by bgeltz** [comment]
It turns out that there's nothing in the SDM about 0x621 or UNCORE_FREQ, so I'm not empowered to add anything at the moment.

**Comment by TomTheBear** [comment]
It's not listed in the SDM, yes. I'll search for the document and send it to you somehow.

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Brad Geltz <notifications@github.com> </div><div>Datum:09.07.2019  19:09  (GMT+01:00) </div><div>An: LLNL/msr-safe <msr-safe@noreply.github.com> </div><div>Cc: Thomas Gruber <Thomas.Roehl@googlemail.com>, Mention <mention@noreply.github.com> </div><div>Betreff: Re: [LLNL/msr-safe] Add MSR_UNCORE_RATIO_LIMIT (#56) </div><div>
</div>It turns out that there's nothing in the SDM about 0x621 or UNCORE_FREQ, so I'm not empowered to add anything at the moment.

**Comment by TomTheBear** [comment]
[Energy Efficient Servers by C. Gough, I. Steiner and W. A. Saunders, page 220](https://link.springer.com/content/pdf/10.1007%2F978-1-4302-6638-9.pdf)
Google doesn't find a public Intel documentation mentioning this register.

**Comment by bgeltz** [comment]
Thanks @TomTheBear.  I'll setup another PR to add that MSR.

**Pull request closed without merging**
