### PR TITLE
IA32_PERF_CTL should only be writable to the lower 16 bits.

### PR DESCRIPTION
**Pull request by sssylvester**
Signed-off-by: Steve S. Sylvester <steve.s.sylvester@intel.com>

### CODE REVIEW

**Comment by slabasan** [comment]
@sssylvester Do we not want to give users the ability to disable Turbo with bit 32 being writable?

**Comment by sssylvester** [comment]
I was just going from the developers manual. Is that an undocumented feature of that MSR?

On Dec 14, 2016, at 3:13 PM, Stephanie Labasan <notifications@github.com<mailto:notifications@github.com>> wrote:


@sssylvester<https://github.com/sssylvester> Do we not want to give users the ability to disable Turbo with bit 32 being writable?

**Comment by slabasan** [comment]
SDM Vol 3 from April 2016 documents that bit 32 is R/W. If the bit is 1, then disengage IDA. From what I can remember, bit 32 is defaulted to 0.

screen shot 2016-12-14 at 3 15 36 pm

**Comment by sssylvester** [comment]
That is for mobile platforms only. Is that from the Silvermont (Atom) section? If so you should ignore it. The Xeon/Xeon Phi sections show that bit as reserved.

Steve

On Dec 14, 2016, at 3:17 PM, Stephanie Labasan <notifications@github.com<mailto:notifications@github.com>> wrote:


SDM Vol 3 from April 2016 documents that bit 32 is R/W. If the bit is 1, then disengage IDA. From what I can remember, bit 32 is defaulted to 0.

[screen shot 2016-12-14 at 3 15 36 pm]<https://cloud.githubusercontent.com/assets/5253432/21205286/39cd459e-c210-11e6-9101-408aa557abd1.png>

**Comment by slabasan** [comment]
Thanks for the catch @sssylvester! Disabling write access to bit 32 for IA32_PERF_CTL: d00ffe1

**Pull request closed without merging**
