### PR TITLE
Make msr_batch_op struct wmask field an input parameter.

### PR DESCRIPTION
**Pull request by cmcantalupo**
Signed-off-by: Christopher M. Cantalupo <christopher.m.cantalupo@intel.com>

### CODE REVIEW

**Comment by slabasan** [comment]
Thank you for your contribution! As I mentioned on #38 , I'd like to spend some cycles testing on our side to double check there are no implications elsewhere in the kernel by changing from an output to an input parameter. Will send an update next week after I've had a chance to talk with some folks here on our side.

**Comment by mcfadden8** [comment]
In order to allow for backwards compatibility for existing applications (users of libmsr), I suggest that this be implemented as a new ioctl call (```X86_IOC_MSR_BATCH_WITH_WMASK_INPUT```) and we leave the semantics for the current ```X86_IOC_MSR_BATCH``` ioctl the same.  This will allow existing applications to still work without change.

The same ```msr_batch_array``` structure could be used with your proposed input semantics.

**Comment by cmcantalupo** [comment]
The only way to do a read / modify / write operation with the existing
semantics is to read the array of values with one ioctl call modify all
values and then write all values with another ioctl call. Is this the
proposed use case for the existing implementation? Seems that the values
may change between the read and write depending on the number of values in
the array and which msr is being written. If this seems like a valid use
case, then the extra ioctl definition could allow for backward
compatibility, but I’m not sure the existing use case makes sense if the
msr being written can be changed by another actor between the ioctl calls.

**Comment by mcfadden8** [comment]
Thanks @cmcantalupo, I see your point.  But, the newer kernel module with the different semantics will most likely break existing usage.  It is probable that the wmask was either being set to zero by the user or left uninitialized when the call is made.  If that user code is unchanged, the call will most likely fail or produce unpredictable results because the wmask will not make sense to the kernel module.

If we simply replace the existing semantics for wmask, then callers will need to behave differently depending upon which version of the kernel module they are talking to.  From a deployment perspective this seems problematic.  I think it would be safest if we had a ```X86_IOC_MSR_BATCH_V2``` ioctl to handle the changed semantics.

**Pull request closed without merging**
