### PR TITLE
Restrict Access to msr_whitelist

### PR DESCRIPTION
**Pull request by bensallen**
Normal users should only have access to the CPU msr-safe devices not msr_batch or msr_whitelist, which should require elevated permissions.

### CODE REVIEW

**Comment by cmcantalupo** [comment]
@bensallen I agree that restricting access to msr_whitelist is critical, however users should have group access to msr_batch which allows batch access though an ioctl interface but is otherwise equivalent to the CPU specific msr access.

**Comment by slabasan** [comment]
Thanks @bensallen and @cmcantalupo for the change. This pull request has been merged with the master branch here: 1876d172fd549868ca3be06d3d7f07fc96b17031.

**Comment by slabasan** [comment]
@bensallen @cmcantalupo : Amending my previous merge. We also agree that privileged access is needed for the whitelist, but the individual site determines what that privilege is.  Assuming root is required will break all of the msr-safe installations that we know of. If you have an alternative suggestion on how to handle this, we'd greatly appreciate it! I will restore the whitelist privileges on the master branch the default settings, letting sites set their own privileges.

**Comment by bensallen** [comment]
@slabasan, if you take a look at the RPM the systemd unit file applies the whitelist configured in /etc/sysconfig/msr-safe. This is or something similar is the correct approach of applying the whitelist. We should not publish default insecure udev rules. Let the site loosen the privileges if they require it.

**Comment by slabasan** [comment]
@bensallen This is another viable solution in setting the default privileges to very restrictive and letting the site loosen the privileges if necessary. Let me speak to some folks internally about how to proceed from here. Thanks again for your suggestions!

**Comment by bensallen** [comment]
@slabasan I should note the approach I mentioned is what's in production at ANL.

**Pull request closed without merging**
