### PR TITLE
Intel Allowlist Templates

### PR DESCRIPTION
**Pull request by infamicstudios**
### Introduces template allowlists containing known and documented MSR's for all supported Intel CPU families:
`06_2AH, 06_2DH, 06_3AH, 06_3CH, 06_3DH, 06_3EH, 06_3FH, 06_45H, 06_46H, 06_47H, 06_4EH, 06_4FH, 06_55H, 06_56H, 06_5EH, 06_66H, 06_6AH, 06_6CH, 06_7DH, 06_7EH, 06_8CH, 06_8DH,  06_8EH, 06_8FH, 06_97H, 06_9AH, 06_9EH, 06_A5H, 06_A6H,  06_BFH`

The goal is to create templates with full coverage to enable safer, easier allowlist creation and customization. 

**It's recommended that the user check the allowlist's MSR comment against the latest revision of the Software Developer Manuals.**

No changes to functionality or source

### CODE REVIEW

**Comment by rountree** [comment]
@infamicstudios Doing a spot check, `06_47h.txt` has unnamed MSRs at the end (lines 331-338).  I'm guessing that's the set of MSRs with much larger addresses and your parser didn't notice.  Can you do a pass and clean those up?

Now that I'm looking at these it would be a "nice to have" if we recorded which table the MSR came from, e.g., 

```
0x000000E7 0x0000000000000000 # "IA32_MPERF" (2-2)
```
Is that more of a 10 minute or 100 minute change?

**Comment by infamicstudios** [comment]
@rountree I'll take a look, I believe that should be a really quick change. In regards to the missing labels, If I am not mistaken they were unlabeled in the source data I'll double-check that. All of the 0xC*XXXXXXX* MSR's are like that in the templates currently.

**Comment by infamicstudios** [comment]
> I'll take a look, I believe that should be a really quick change. In regards to the missing labels, If I am not mistaken they were unlabeled in the source data I'll double-check that. All of the 0xC_XXXXXXX_ MSR's are like that in the templates currently.

Ah nevermind they are just formatted differently than the rest of the data. I'll fix that up.

**Comment by infamicstudios** [comment]
Closing this and incorporating the changes into a new pull request.

**Pull request closed without merging**
