### PR TITLE
Add MSR_UNCORE_PERF_STATUS

### PR DESCRIPTION
**Pull request by bgeltz**
- Status register compliment to MSR_UNCORE_RATIO_LIMIT.

Signed-off-by: Brad Geltz <brad.geltz@intel.com>

### CODE REVIEW

**Comment by bgeltz** [comment]
@cmcantalupo @slabasan Please take a look when you have a moment.  This is the status register we discussed in #56.

**Comment by slabasan** [comment]
@bgeltz Any reason the lower 7 bits are writable for this MSR? I would have expected it to have the same RO writemask as the other PERF_STATUS registers.

**Comment by bgeltz** [comment]
Nice catch @slabasan.  Yep, that was unintentional.  I just updated the commit.

**Comment by slabasan** [comment]
Thanks, looks good to me!

**Pull request merged**
