### PR TITLE
Using inode_lock and inode_unlock instead of ...

### PR DESCRIPTION
**Pull request by maiterth**
Using inode_lock and inode_unlock instead of mutex_lock and mutex_unlock.
This should work with changes since kernel 4.5.0.
Also resolves issues #11.

### CODE REVIEW

**Comment by slabasan** [comment]
Thanks @maiterth. @connorimes had an earlier solution using `down_write` and `up_write`. Do you know if there are any implications between using `inode_lock/unlock` vs. `down/up_write`?

**Comment by connorimes** [comment]
See #12 - I'll defer to anybody with actual kernel experience though.

Both your `inode_lock` and `inode_unlock` functions call `mutex_lock` - is that intentional, or should the second one be `mutex_unlock`?

**Comment by maiterth** [comment]
I guess the solutions lies in the inode_unlock calls up_write(&inode->i_rwsem);
and inode_lock calls down_write(&inode->i_rwsem);

compare for
linux/include/linux/fs.h (search for inode_lock)
and 
linux/kernel/locking/rwsem.c (for up_write and down_write)

**Comment by connorimes** [comment]
FYI, this doesn't compile in kernel 4.4 - `inode_lock` and `inode_unlock` are being redefined.

**Pull request closed without merging**
