### PR TITLE
Fix build with recent kernels.

### PR DESCRIPTION
**Pull request by hramrach**

### CODE REVIEW

**Comment by hramrach** [comment]
The Ubuntu 18.04 test is failing on Master already, maybe it should be dropped?

**Comment by rountree** [comment]
@hramrach Apologies for not getting to this sooner.  We're discussing what to do about test coverage.

**Comment by hramrach** [comment]
You can try to test everything.

And there is also another approach: to test some things, and if the things you test don't break and the patch looks sane assume that it may help in some cases that you do not test.

**Comment by rountree** [comment]
Fixes #146

**Comment by rountree** [comment]
@hramrach We tested locally on a pre-release version of mantic using 6.5.0-5-generic.  Looks good.  I expect this will be applied in the next couple of days.

**Review by rountree — APPROVED** [review]
Tested on gilia/mantic/6.5.0-5-generic.  Example program works as expected.

Appreciate the help, thanks!

**Comment by slabasan** [comment]
Hi @hramrach, Thank you for your contribution and apologies for the delay in getting this merged. We have deprecated ubuntu-18.04, and will merge this PR in.

**Pull request merged**
